sudo: false

language: python

env:
  global:
    # Doctr deploy key for devitocodes/devito
    - secure: "hAFf5Vc1VrgC8aotrgAlJuAE8V1BhShGXSmalLtgHQtTqAhndOXGB5erGnTtTcjayVT8EhapRpHKd9z2nxAg03ijKDMQSkC2UD4Cvby6oeSs7/MD7D84ogaI5gPEF8RCyoKz9spK8fM9Z4c4wxUZYDTn3sD/fwEaD1PMCMxeQ4X785PeoAcZi/u0AM6utGw5AaTdLll+KVSvJQJpq9pg7ICHNOCq9d7K3T4oFlto97MXP3clkju48Jl2lbXdM+oREuKyE5l4/mFNUtvBg3g1tXOTdOQnQhywYCM5AbCfdNa78nXFg9q7UmcKk42zLvFh8tWLJsvKCo+pTGGTZ5bmkg5oZXfAE/lTwcBdd9NxWYMjirj6z6v0UlHLpSvugtLobwf2p06yEb3G0HVCzLzPzTsIKA/8m67pCCbuSQIS7W7N35PBWudyi4xDQZr/jraDI6Z3WM+iH6eD3YeQ9YhJaTE5ivpiZ850hEPUD+hvontw8rRDt7kgsuoj5O5NBQtSC52JJBNAK0fS9BZC4M4lYBGpMAws40J/uZodS+0aY5mZXW2vT9vGQmmfyopsV0rf0qp4AHUQAaQ7nmtu4v7eoj+a0UohQKOjiN1CvLvdZRimOJtOWASdAxstIiOBBaGMn/SHuDerfZDmZbZlaQFEkjVw+5dqTFUnNKaHFZhYUqU="
    - DEVITO_LOGGING: "INFO"

matrix:
  include:
    - python: 3.7
      dist: xenial
      os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test     # For gcc 4.9, 5 and 7
          packages:
            - gcc-9
            - g++-9
      env: DEVITO_ARCH=gcc-9 DEVITO_OPENMP=0 RUN_EXAMPLES=False INSTALL_TYPE=conda RUN_BENCHMARKS=True MPI_INSTALL=0

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test     # For gcc 4.9, 5 and 7

before_install:
  - if [[ "$MPI_INSTALL" == '1' ]]; then
      sudo apt-get install -y -q mpich libmpich-dev;
      export MPICH_CC=$DEVITO_ARCH;
    fi
  # Setup anaconda
  - if [[ $INSTALL_TYPE == 'conda' ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      hash -r;
      conda config --set always_yes yes --set changeps1 no;
      conda info -a;
      export COV="--cov";
    fi

install:
  # Install devito with conda
  - if [[ $INSTALL_TYPE == 'conda' ]]; then
      sed -i -E 's/(python=)(.*)/\1'$TRAVIS_PYTHON_VERSION'/' environment.yml;
      conda env create -q -f environment.yml;
      source activate devito;
      conda update -q conda;
      pip install -e .;
      conda list;
    fi
  - if [[ $MPI_INSTALL == '1' ]]; then
      pip install -r requirements-optional.txt;
    fi
  - if [[ $RUN_BENCHMARKS == 'True' ]]; then
      pip install asv;
    fi

  # Install devito with pip
  - if [[ $INSTALL_TYPE == 'pip_setup' ]]; then python setup.py install; fi
  - if [[ $MPI_INSTALL == '1' ]]; then pip install -e .[extras]; fi

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - if [[ $DEVITO_BACKEND == 'yask' ]]; then
      conda install swig; cd ../;
      git clone https://github.com/devitocodes/yask.git;
      cd yask; make compiler-api; pip install -e .; cd ../devito;
    fi

script:
  - flake8 --builtins=ArgumentError .
  # Run benchmarks with Airspeed Velocity
  - if [[ $RUN_BENCHMARKS == 'True' ]]; then
      cd benchmarks/regression;
      bash merge_history.sh;
      asv run HASHFILE:merge_history.txt;
      asv publish;
      asv gh-pages;
      cd ../..;
    fi
  # Code coverage and documentation generation
  - if [[ $INSTALL_TYPE == 'conda' ]]; then
      codecov;
      cd docs;
      make html;
      cd ..;
    fi
  # Docs deployment only once from a single build
  - if [[ $DEVITO_ARCH == 'gcc-5' ]]; then
          set -e;
          pip install doctr;
          doctr deploy . --built-docs docs/_build/html --key-path .deploy_key.enc;
    fi
